# -*- coding: utf-8 -*-
"""assignment1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IrMXSG6a8Yxkk1yrYq_SPkyEnuTkIoC1
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.DataFrame({
    'order_time':['6:00','7:00','7:00','9:00'],
    'delivery_time':['6:15','7:20','7:10','9:05'],
    'delivery_partner':["venkat","chetan","ravi","varma"],
    'delivery_area':["mdp","kdr","ang","mits"],
    'customer_rating':[5,5,4,3]
})
print(df)
df['order_time'] = pd.to_datetime(df['order_time'], format='%H:%M')
df['delivery_time'] = pd.to_datetime(df['delivery_time'], format='%H:%M')
c=max(df['customer_rating'])
cr=[]*len(df['order_time'])
for i in range(len(df['order_time'])):
    if df['customer_rating'][i]==c:
        cr.append(df['delivery_partner'][i])
dt=[]*len(df['order_time'])
for i in range(len(df['order_time'])):
    dt.append(df['delivery_time'][i] - df['order_time'][i])
print(dt)
print("average delevery time:",np.mean(dt))
print("peak ordered hours",df['order_time'].dt.hour.value_counts().idxmax())
print("top rated delevery partner:",cr)
print("most delayed area:",df['delivery_area'][dt.index(max(dt))])
plt.title("customer rating")
sns.barplot(x=df['delivery_partner'],y=df['customer_rating'])
plt.show()
plt.title("delayed area")
sns.barplot(x=df['delivery_area'],y=dt)
plt.show()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.DataFrame({
    'product_purchases':["milk","eggs","jam","bread","milk"],
    'cart_abandonment':["dumble","yoga mat","sugar","pepper","butter"],
    'customer_ratings':[4,5,3,2,4],
    'payment_methods':["upi","cash","card","upi","upi"]
})
print(df)
plt.title("most sold products")
plt.pie(df['product_purchases'].value_counts(),labels=df['product_purchases'].value_counts().index,autopct='%1.1f%%')
plt.show()
print("\n most sold products",df['product_purchases'].mode())
plt.title("payment methods")
plt.pie(df['payment_methods'].value_counts(),labels=df['payment_methods'].value_counts().index,autopct='%1.1f%%')
plt.show()
print("\n most used payment method",df['payment_methods'].mode())
plt.title("customer ratings")
sns.barplot(x=df['product_purchases'],y=df['customer_ratings'])
plt.show()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import datetime
df=pd.DataFrame({
    'transactions':[10000,5000,2600.23,650,240.03,50],
    'location':["kdp","kur","chr","mdp","ang","kdr"],
    'time':['23:00','23:30','03:15','04:45','06:00','12:05'],
    'account_activity':["active","active","unactive","active","unactive","active"]
})
df['time']=pd.to_datetime(df['time'],format='%H:%M')
print(df)
print("\nunusual transactions:")
for i in range(len(df['transactions'])):
  if df['transactions'][i] != int(df['transactions'][i]):
    print(df['transactions'][i])
plt.title("transaction")
sns.barplot(x=df['account_activity'],y=df['transactions'])
plt.show()
print("\nrisk handling")
for i in range(len(df['transactions'])):
  if df['time'][i].time() > datetime.time(10, 0) and df['account_activity'][i]=='active':
    print(df['transactions'][i],df['time'][i],df['location'][i])
plt.title("location")
sns.barplot(x=df['location'],y=df['transactions'])
plt.show()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.DataFrame({
    'daily_sales':[7000,3000,1500,4000],
    'product_stock':[10000,15000,10000,7000],
    'expiry_dates':['2026-05-15','2026-07-29','2026-08-17','2026-08-26'],
    'seasonal_demand':["summar","rainy","autumn","winter"]
})
df['expiry_dates']=pd.to_datetime(df['expiry_dates'])
print(df)
pr = df['product_stock'] - df['daily_sales']
print(np.mean(pr))
print(" product fast moving in:")
for i in range(len(df['daily_sales'])):
  if pr[i]>=np.mean(pr):
    print(df['seasonal_demand'][i])
print(" product slow moving in:")
for i in range(len(df['daily_sales'])):
  if pr[i]<np.mean(pr):
    print(df['seasonal_demand'][i])