d <-c(10,20,30,40,50,50,60,80,40,40)
print("dataset:")
print(d)
mean_val<-mean(d)
print(paste("Mean=",mean_val))
median_val<-median(d)
print(paste("median=",median_val))
mode_function<-function(x){
  uniq_values<-unique(x)
  uniq_values[which.max(tabulate(match(x,uniq_values)))]
}
mode_val<-mode_function(d)
print(paste("Mode=",mode_val))
max_val<-max(d)
print(paste("maximum=",max_val))
min_val<-min(d)
print(paste("minimum=",min_val))
variance_val<-var(d)
print(paste("varance=",variance_val))
sd_val<-sd(d)
print(paste("standard deviation=",sd_val))
summary(d)
barplot(d)
lines(d)
hist(d)
pie(d) 
boxplot(d)
scatter.smooth(d)
