# -*- coding: utf-8 -*-
"""visualization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PpNJyVmYA_6V_5gXMiS6Z_IiOasU2C7u
"""

import numpy as np
import pandas as pd
import statistics
import matplotlib.pyplot as plt
m_names=["venkat","chetan","venkatesh","yash","ravi"]
age=[20,22,26,24,25]
work_hours=[2,3,1,4,2.5]
calories_burned=[550,600,300,650,500]
print("--fitness center datset--")
for i in range(len(m_names)):
    print(m_names[i],age[i],work_hours[i],calories_burned[i])

avg_workout=sum(work_hours)/len(work_hours)
print("average workout hours=",avg_workout)

highest_calories=max(calories_burned)
print("highest calories burned=",highest_calories)

lowest_workout=min(work_hours)
print("lowest workout hours=",lowest_workout)

median_calories=statistics.median(calories_burned)
print("median calories burned=",median_calories)

std_dev=statistics.stdev(calories_burned)
print("standard deviation=",std_dev)

index=calories_burned.index(highest_calories)
print("most active member=",m_names[index])

plt.title("fitness analysis")
plt.xlabel("members")
plt.ylabel("calories")
plt.bar(m_names,calories_burned)
plt.show()
plt.title("work hours")
plt.pie(work_hours,labels=m_names)
plt.show()
plt.title("workout hours")
plt.xlabel("age")
plt.ylabel("hours")
plt.stem(age,work_hours)
plt.show()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
data=pd.read_csv("/content/gym_members_exercise_tracking_synthetic_data.csv")
plt.title("fitness")
plt.xlabel("fat%")
plt.ylabel("calories_burned")
sns.scatterplot(data=data,x='Fat_Percentage',y='Calories_Burned')
plt.show()
sns.scatterplot(data=data,x='Water_Intake (liters)',y='Workout_Frequency (days/week)',size='Age',sizes=(20,200),hue='Workout_Type')
plt.title("water intake vs workout frequency")
plt.xlabel("water intake")
plt.ylabel("workout frequency")
plt.show()
plt.title("workout")
plt.pie(data['Workout_Type'].value_counts(),labels=data['Workout_Type'].value_counts().index)
plt.show()
plt.hist(data['Age'],bins=10,color='blue',edgecolor='green')
plt.title("age distribution")
plt.xlabel("age")
plt.ylabel("frequency")
plt.show()
sns.lineplot(data=data,x='Fat_Percentage',y='Max_BPM')
plt.title("BPM rate")
plt.xlabel("fat%")
plt.ylabel("Max_BPM rate")
plt.show()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
cust_name=["venkat","chetan","venkey","sunny"]
cust_area=["kdp","hyd","mdp","hyd"]
cust_recharge=[240,299,580,2000]
cust_recharge_type=["smart phone","5G plan  ","Data plan","gamming"]
internet_speed=[5,7,3,8]
payment_failure=[3,6,5,9]
delevery_charge=[2,3,5,8]
print("--customer recharge--")
print("customer\tarea recharge\t type\t\tspeed\tpayment_f\tdelevery")
for i in range(len(cust_name)):
    print(f"{cust_name[i]}\t\t{cust_area[i]}\t\t{cust_recharge[i]}\t\t{cust_recharge_type[i]}\t{internet_speed[i]}\t\t{payment_failure[i]}\t\t\t{delevery[i]}")
plt.title("payment diagnosis")
plt.xlabel("customer")
plt.ylabel("payment failure")
plt.bar(cust_name,payment_failure)
plt.show()
for i in range(len(cust_name)):
  if payment_failure[i]>3:
    print(cust_name[i])
print("\n\n")
plt.title("customer recharge plan")
plt.pie(cust_recharge,labels=cust_name,autopct='%1.f%%')
plt.show()
for i in range(len(cust_name)):
  if cust_recharge[i]>300:
    print(cust_name[i])
print("\n\n")
plt.title("internet speed")
plt.xlabel("area")
plt.ylabel("internet speed")
plt.scatter(cust_area,internet_speed)
plt.show()
for i in range(len(cust_name)):
  if internet_speed[i]<5:
    print(cust_name[i])
print("\n\n")
plt.title("delevery")
plt.xlabel("customer")
plt.ylabel("delevery")
plt.stem(cust_name,delevery)
plt.show()
for i in range(len(cust_name)):
  if delevery[i]>3:
    print(cust_name[i])
print("\n\n-------root cause-------")
for i in range(len(cust_name)):
  if payment_failure[i]>3 and internet_speed[i]<5 and delevery[i]>3:
    print(cust_name[i])

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv("/content/WA_Fn-UseC_-Telco-Customer-Churn.csv")
plt.title("payment_methods")
plt.pie(df['PaymentMethod'].value_counts(),labels=df['PaymentMethod'].value_counts().index,autopct='%1.f%%')
plt.show()
plt.title("internet bill")
plt.bar(df['InternetService'],df['MonthlyCharges'])
plt.show()
plt.title("network sevice on tenure")
if df['OnlineSecurity'][0]=='No':
  plt.plot(df['tenure'],df['OnlineSecurity'])
plt.show()
plt.title("contract type")
plt.pie(df['Contract'].value_counts(),labels=df['Contract'].value_counts().index,autopct='%1.f%%')
plt.show()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv("/content/cleaned_global_water_consumption.csv")
avg_consumption_by_country = df.groupby('Country')['Total Water Consumption (Billion Cubic Meters)'].mean()
plt.title("water consumption")
plt.bar(df['Year'],df['Total Water Consumption (Billion Cubic Meters)'])
plt.show()
countries_with_high_consumption_years = {}

for i in range(len(df['Total Water Consumption (Billion Cubic Meters)'])):
  country = df['Country'][i]
  year = df['Year'][i]
  current_consumption = df['Total Water Consumption (Billion Cubic Meters)'][i]
  country_average_consumption = avg_consumption_by_country[country]

  if current_consumption > country_average_consumption:
    if country not in countries_with_high_consumption_years:
      countries_with_high_consumption_years[country] = []
    countries_with_high_consumption_years[country].append(year)

for country, years in countries_with_high_consumption_years.items():
  print(f"{country}: {', '.join(map(str, sorted(years)))}")

print("\n")
plt.title("water consumtion in agriculture")
plt.bar(df['Year'],df['Agricultural Water Use (%)'])
plt.show()
print("\n")
plt.title("water consumption in industry")
plt.plot(df['Year'],df['Industrial Water Use (%)'])
plt.show()
print("\n")
plt.figure(figsize=(10, 10))
plt.title("Average Water Consumption per Country")
plt.pie(avg_consumption_by_country, labels=avg_consumption_by_country.index, autopct='%1.1f%%', startangle=90)
plt.axis('equal')
plt.show()

import numpy as np
import pandas as pd
data={
    'day':[1,2,3,4,5,6,7],
    'Water_Consumption':[1000,3000,1500,4000,2300,900,5000]
}
df = pd.DataFrame(data)
print("Dataset:")
print(df)
daily_inc=[]
for i in range(len(df['Water_Consumption'])-1):
    daily_inc.append(abs(df['Water_Consumption'][i+1]-df['Water_Consumption'][i]))
print(f"Daily Water Consumption: {daily_inc}")
avg=sum(daily_inc)/len(daily_inc)
print(f"Average Water Consumption: {avg}")
water_Tank = 10000
if (df["Water_Consumption"][len(df["Water_Consumption"])-1]+avg)>water_Tank:
    print("not sufficient")
else:
    print("Yes we can use water")

import numpy as np
import pandas as pd
df=pd.DataFrame({
    'name':["venkat","chetan","venkey","ben"],
    'age':[21,80,75,10],
    'condition':["good","cretical","better","healthy"],
    'oxygen_level':[85,78,89,96]
})
print(df)
no_of_beds=3
beds=[None] * no_of_beds
print(beds)

beds_allocated_count = 0
for i in range(len(df)+1):
  if beds_allocated_count < no_of_beds:
   if df['condition'][i]=="cretical":
      if beds[i] is None:
         beds[i] = df['name'][i]
         beds_allocated_count += 1
   elif df['oxygen_level'][i]<=85:
      if beds[i] is None:
        beds[i] = df['name'][i]
        beds_allocated_count += 1
   elif df['age'][i]>=75:
      if beds[i] is None:
        beds[i] = df['name'][i]
        beds_allocated_count += 1
print(beds)